#resolver: lts-9.2
resolver: nightly-2017-12-31
packages:
- '.'
- location:
    git: https://github.com/serokell/acid-state.git
    commit: master
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit : master
  extra-dep: true

nix:
    packages: [openssh,git]

extra-deps:
- aeson-extra-0.4.0.0
- aeson-1.1.2.0
- containers-0.5.10.2
- fmt-0.5.0.0
- time-units-1.0.0
- recursion-schemes-5
- universum-1.0.2

flags: {}
extra-package-dbs: []
